<?php
	include "header.php";
?>

<?php
	include "footer.php";
?>

<h1> Frågor och Svar</h1>

<p>Vi har bett Marie Houston, VD för Schratch Nails, svara på tio vanliga frågor om naglar.
<br><br><strong>1. Varför skivar sig naglarna så lätt?</strong><br>Naglarna blir uttorkade av starka rengöringsmedel, vatten, handsprit, torr och varm inomhusluft osv. Keratinet som ligger likt ett klister mellan naglarnas skikt torkar ut och det resulterar i en nagel som skivar och delar sig. Nagelolja varje dag är lösningen, använd den lika regelbundet som du smörjer in ansiktet.<br><br><strong>2. Jag har svårt att få lacket att sitta ens en dag, vad gör jag för fel?</strong><br>Gör rent nagelytan ordentligt innan du sätter på nytt lack. Tvätta händerna, använd nagelbandsremover, nagelbandsverktyg och nagelborste och se till att få bort den tunna nagelbandshuden som kryper upp på nagelplattan. Polera in NailFood med nagelpolerare och vänta med att smörja in händerna tills efter du lackat.<br><br><strong>3. Lackade naglar är jättesnyggt men jag hinner aldrig vänta på att det ska torka. Finns det några genvägar?</strong><br>Gör det i flera steg: rengöring och oljepolering på kvällen, grunda med baslack dagen efter osv. Det viktiga är att ytan på nageln är helt ren när du lackar, du kan inte först spraya håret i badrummet och sedan sätta dig för att lacka. Det finns också produkter som får lacket att torka snabbare. Ett annat tips är att ha en färdig dukad manikyrbricka att plocka fram när du tex sitter och tittar på TV.<br><br><strong>4. Kan man laga en trasig nagel?</strong><br>Det kan man, även om det är lite pyssel och du behöver vara noggrann. Det finns ett speciellt mendingkit med glasfiber och silkesväv från Scratch.<br><br><strong>5. Mina naglar är ojämna, finns det någon hjälp?</strong><br>Så kallade ridgefillers är underlack som fyller ut ytan och gör den jämnare, precis som en primer under din foundation.<br><br><strong>6. Kan man äta något som gör naglarna starkare?</strong><br>Öljäst, åkerfräkenextrakt och magnesium är ämnen som anses kunna stärka naglarna. .<br><br><strong>7. Går det att använda samma remover till byggda naglar som till naturliga naglar?</strong><br>Ja, så länge den inte innehåller aceton men läs på flaskan vad som gäller innan du väljer.<br><br><strong>8. Jag har fått en ful ton på nagelytan. Går det att få bort?</strong><br>Det finns polerande crèmer, Nail Whitening Paste som tar bort missfärgningar. Du använder dem tillsammans med en nagelborste. Försvinner inte färgen kan du använda No Yellow eller UVlack som neutraliserar den .<br><br><strong>9. Varför får man vita fläckar på naglarna?</strong><br>Det handlar ofta om att luft hamnat mellan naglarnas olika skick, det kan uppstå av ett lätt slag på nagelroten.<br><br><strong>10. Mina naglar får ofta små sprickor långt ner på sidorna. Vad gör jag för fel?</strong><br>Det kan bero på att du filar in för mycket på sidorna, då förlorar naglarna sitt naturliga stöd. Fila bara på det som sticker utanför den fria kanten.</p>